In [1]:
import pandas as pd
pd.set_option("display.max_columns", 500)
pd.set_option("display.max_rows", 500)

## Importamos los archivos

In [2]:
df_bajas = pd.read_feather('../../data/processed/periodos_baja_x_cif_id.feather')

In [3]:
df_pagos = pd.read_feather('../../data/processed/pagos_x_cif_id.feather')

In [4]:
df_interacciones = pd.read_feather('../../data/processed/interacciones_tipo_periodo_x_cif_id.feather')

In [5]:
df_clientes = pd.read_feather('../../data/interim/clientes.feather')

In [6]:
df_clientes = df_clientes.rename(columns={"ID":"CIF_ID"})

In [7]:
df_siniestros = pd.read_feather('../../data/processed/siniestros_x_cif_id.feather')

## Verificamos que todos se puedan combinar con la tabla Bajas

In [8]:
def check_merge(df1,df2,field):
    return len(set(df1[field].unique()).intersection(set(df2[field].unique()))) / len(df1[field].unique())

In [9]:
df_pagos.columns

Index(['CIF_ID', '1_SITUACION_AM', '1_SITUACION_CT', '1_SITUACION_EP',
       '2_SITUACION_AM', '2_SITUACION_CT', '2_SITUACION_EP', '3_SITUACION_AM',
       '3_SITUACION_CT', '3_SITUACION_EP',
       ...
       'demora_pago_4', 'demora_pago_5', 'demora_pago_6', 'demora_pago_7',
       'demora_pago_8', 'demora_pago_9', 'demora_pago_10', 'demora_pago_11',
       'demora_pago_12', 'demora_pago_13'],
      dtype='object', length=142)

In [10]:
check_merge(df_bajas, df_pagos, "CIF_ID")

0.9678489898349993

In [11]:
check_merge(df_bajas, df_clientes, "CIF_ID")

1.0

In [12]:
check_merge(df_bajas, df_interacciones, "CIF_ID")

0.9979883390348918

In [13]:
check_merge(df_bajas, df_siniestros, "CIF_ID")

0.24384998566274782

## Merge entre tablas

In [14]:
len(df_bajas)

899754

In [15]:
len(df_interacciones)

1636467

In [16]:
len(df_pagos)

870826

In [17]:
len(df_clientes)

11887104

In [18]:
len(df_siniestros)

219405

In [19]:
df_bajas_int =  pd.merge(df_bajas, df_interacciones, on=['CIF_ID'], how='left')

In [20]:
df_bajas_int.head()

,CIF_ID,hist_polizas,periodo_baja,1_TIPOINT_A,1_TIPOINT_I,1_TIPOINT_O,2_TIPOINT_A,2_TIPOINT_I,2_TIPOINT_O,3_TIPOINT_A,3_TIPOINT_I,3_TIPOINT_O,4_TIPOINT_A,4_TIPOINT_I,4_TIPOINT_O,5_TIPOINT_A,5_TIPOINT_I,5_TIPOINT_O,6_TIPOINT_A,6_TIPOINT_I,6_TIPOINT_O,7_TIPOINT_A,7_TIPOINT_I,7_TIPOINT_O,8_TIPOINT_A,8_TIPOINT_I,8_TIPOINT_O,9_TIPOINT_A,9_TIPOINT_I,9_TIPOINT_O,10_TIPOINT_A,10_TIPOINT_I,10_TIPOINT_O,11_TIPOINT_A,11_TIPOINT_I,11_TIPOINT_O,12_TIPOINT_A,12_TIPOINT_I,12_TIPOINT_O,13_TIPOINT_A,13_TIPOINT_I,13_TIPOINT_O
0,571.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,NaN,2.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN,2.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,4.0
1,573.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,1.0
2,1009.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0
3,1075.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,11.0,NaN,NaN,1.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,16.0,14.0,NaN,5.0,4.0,NaN,2.0,4.0,NaN,2.0,2.0
4,1103.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,NaN,NaN,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0,NaN,NaN,1.0,NaN,NaN,2.0

In [21]:
df_bajas_int_sini =  pd.merge(df_bajas_int, df_siniestros, on=['CIF_ID'], how='left')

In [22]:
df_bajas_int_sini = df_bajas_int_sini.fillna(0)

In [23]:
df_bajas_int_sini.head()

,CIF_ID,hist_polizas,periodo_baja,1_TIPOINT_A,1_TIPOINT_I,1_TIPOINT_O,2_TIPOINT_A,2_TIPOINT_I,2_TIPOINT_O,3_TIPOINT_A,3_TIPOINT_I,3_TIPOINT_O,4_TIPOINT_A,4_TIPOINT_I,4_TIPOINT_O,5_TIPOINT_A,5_TIPOINT_I,5_TIPOINT_O,6_TIPOINT_A,6_TIPOINT_I,6_TIPOINT_O,7_TIPOINT_A,7_TIPOINT_I,7_TIPOINT_O,8_TIPOINT_A,8_TIPOINT_I,8_TIPOINT_O,9_TIPOINT_A,9_TIPOINT_I,9_TIPOINT_O,10_TIPOINT_A,10_TIPOINT_I,10_TIPOINT_O,11_TIPOINT_A,11_TIPOINT_I,11_TIPOINT_O,12_TIPOINT_A,12_TIPOINT_I,12_TIPOINT_O,13_TIPOINT_A,13_TIPOINT_I,13_TIPOINT_O,periodo_sini_1,periodo_sini_2,periodo_sini_3,periodo_sini_4,periodo_sini_5,periodo_sini_6,periodo_sini_7,periodo_sini_8,periodo_sini_9,periodo_sini_10,periodo_sini_11,periodo_sini_12,periodo_sini_13,periodo_liquidacion_sini_1,periodo_liquidacion_sini_2,periodo_liquidacion_sini_3,periodo_liquidacion_sini_4,periodo_liquidacion_sini_5,periodo_liquidacion_sini_6,periodo_liquidacion_sini_7,periodo_liquidacion_sini_8,periodo_liquidacion_sini_9,periodo_liquidacion_sini_10,periodo_liquidacion_sini_11,periodo_liquidacion_sini_12,periodo_liquidacion_sini_13,periodo_rechazo_sini_1,periodo_rechazo_sini_2,periodo_rechazo_sini_3,periodo_rechazo_sini_4,periodo_rechazo_sini_5,periodo_rechazo_sini_6,periodo_rechazo_sini_7,periodo_rechazo_sini_8,periodo_rechazo_sini_9,periodo_rechazo_sini_10,periodo_rechazo_sini_11,periodo_rechazo_sini_12,periodo_rechazo_sini_13
0,571.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,0.0,2.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,2.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,573.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1009.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1075.0,0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1,-1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,11.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,16.0,14.0,0.0,5.0,4.0,0.0,2.0,4.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1103.0,0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1,-1,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
from functools import reduce
df_merged = reduce(lambda  left,right: pd.merge(left, right, on=['CIF_ID'], how='inner'), [df_bajas_int_sini, df_pagos, df_clientes])

In [25]:
df_merged.shape

(870826, 224)

### Guardamos la tabla completa

In [26]:
df_merged.to_feather('../../data/processed/merged_data_13_periods.feather')

---

In [27]:
"], [".join(set([''.join([s for s in col if not s.isdigit()]) for col in df_merged.columns]))

'_COBRO_SJ], [_SITUACION_PP], [_TIPOINT_I], [_COBRO_PP], [CIF_ID], [_COBRO_BA], [demora_pago_], [_SITUACION_CT], [_TIPOINT_A], [_COBRO_CC], [POSICION_IVA], [hist_polizas], [periodo_sini_], [periodo_liquidacion_sini_], [_COBRO_TA], [_SITUACION_AM], [_TIPOINT_O], [periodo_baja], [periodo_rechazo_sini_], [_SITUACION_EP], [ANO_DE_NACIMIENTO], [MONTO_PAGO_'